# Generated by Django 4.1.2 on 2022-11-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='group',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
